apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo-app
  namespace: django-todo-app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-todo-app
  template:
    metadata:
      labels:
        app: django-todo-app
    spec:
      containers:
      - name: django-todo-app
        image: robinthakur00/django-todo-app:latest
        ports:
        - containerPort: 8000 
