apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: django-todo-app
  name: django-todo-app
  namespace: django-todo-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-todo-app
  template:
    metadata:
      labels:
        app: django-todo-app
    spec:
      containers:
        - image: 'robinthakur00/django-todo-app:latest'
          name: django-todo-app
          ports:
            - containerPort: 8000
