apiVersion: v1
kind: Service
metadata:
  name: django-todo-app-service
spec:
  selector:
    app: django-todo-app
  ports:
    - protocol: TCP
      port: 80 # Port you want to expose externally
      targetPort: 8000 # Port your app is running inside the container
  type: LoadBalancer # Use 'NodePort' if LoadBalancer is not available
