apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: django-todo-app
  name: django-todo-app-service
  namespace: django-todo-app-ns
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: django-todo-app
  type: NodePort